# Generated by Django 3.1.5 on 2021-01-23 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=20)),
                ('last_Name', models.CharField(max_length=20)),
                ('contact', models.PositiveIntegerField()),
                ('email', models.EmailField(default='@email.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RAWM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('color', models.CharField(default='white', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
                ('ACCN', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SupplierRAWM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, default=None)),
                ('quantity', models.PositiveIntegerField()),
                ('RAWM_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rawm')),
                ('Sup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gusset', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gauge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wast', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raw_for_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('RAWM_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rawm')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateTimeField(auto_created=True)),
                ('quantity', models.PositiveIntegerField()),
                ('pay_date', models.DateTimeField(default=None)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
