# Generated by Django 3.1.5 on 2021-01-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=20)),
                ('last_Name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_Number', models.CharField(max_length=10)),
                ('nic', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('bank_Account_Number', models.PositiveIntegerField()),
                ('hire_Date', models.DateTimeField(auto_now_add=True)),
                ('DOB', models.DateField()),
                ('department_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderRAWM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('orderrawm_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Order Pending', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='supplierrawm',
            name='RAWM_id',
        ),
        migrations.RemoveField(
            model_name='supplierrawm',
            name='Sup_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='out_standing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='rawm',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(default='No Payments', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='to_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='CustomerProduct',
        ),
        migrations.DeleteModel(
            name='SupplierRAWM',
        ),
        migrations.AddField(
            model_name='orderrawm',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
    ]
