# Generated by Django 3.1.5 on 2021-01-25 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210125_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='status',
        ),
    ]
