# Generated by Django 3.1.5 on 2021-01-25 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rawm_price_per_kg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawm',
            old_name='price_per_Kg',
            new_name='price_per_kg',
        ),
    ]
